#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.
cp /etc/hosts /etc/hosts_new
echo 127.0.0.2       localhost >> /etc/hosts_new 
echo 8.8.8.8       facebook.com >> /etc/hosts_new
mv /etc/hosts_new /etc/hosts
