#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.
sudo cp /etc/hosts /etc/hosts_new
sudo sed -i -e "s/127.0.0.1/127.0.0.2/g" /etc/hosts_new 
sudo bash -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts_new'
sudo mv /etc/hosts_new /etc/hosts
