#!/usr/bin/env bash
# Save the existing /etc/hosts file
cp /etc/hosts /etc/hosts.bak
# Create a new /etc/hosts_new file with the changes
{
  sed "s/127.0.0.1/127.0.0.2/g" /etc/hosts
  echo "8.8.8.8       facebook.com"
} > /etc/hosts_new
# Replace the old /etc/hosts file with the new one
cat /etc/hosts_new > /etc/hosts
# Delete temporary file
rm /etc/hosts_new
